/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.io.FileNotFoundException;
import java.util.List;
import dao.IMiniBusDAO;
import oracle.OracleDataSourceDAO;
import metier.MiniBus;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import oracle.OracleMiniBusDAO;

/**
 *
 * @author xtz_j
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        listeMinibus = minibusDAO.getLesMinibus();
        System.out.println(listeMinibus.toString());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMatchDialog = new javax.swing.JDialog();
        player2ComboxBox = new javax.swing.JComboBox<>();
        player1ComboxBox = new javax.swing.JComboBox<>();
        player3ComboxBox = new javax.swing.JComboBox<>();
        player4ComboxBox = new javax.swing.JComboBox<>();
        versusLabel = new javax.swing.JLabel();
        lineRefereesSelectionPane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ballBoySelectionPane = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        mainRefereeComboBox = new javax.swing.JComboBox<>();
        mainRefereeLabel = new javax.swing.JLabel();
        lineRefereeLabel = new javax.swing.JLabel();
        ballBoyLabel = new javax.swing.JLabel();
        matchDateLabel = new javax.swing.JLabel();
        matchDateComboBox = new javax.swing.JComboBox<>();
        matchTimeLabel = new javax.swing.JLabel();
        matchTimeComboBox = new javax.swing.JComboBox<>();
        playerLabel = new javax.swing.JLabel();
        confirmAddButton = new javax.swing.JButton();
        cancelAddButton = new javax.swing.JButton();
        addMatchInfoLabel = new javax.swing.JLabel();
        addMatchTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        matchDateComboBox1 = new javax.swing.JComboBox<>();
        matchDateLabel1 = new javax.swing.JLabel();
        saveCourtDialog = new javax.swing.JDialog();
        saveDateLabel = new javax.swing.JLabel();
        saveDateComboBox = new javax.swing.JComboBox<>();
        saveTimeLabel = new javax.swing.JLabel();
        saveTimeComboBox = new javax.swing.JComboBox<>();
        saveTitleLabel = new javax.swing.JLabel();
        confirmSaveButton = new javax.swing.JButton();
        cancelSaveButton = new javax.swing.JButton();
        saveCourtInfoLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        courtComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addMatchButton = new javax.swing.JButton();
        saveCourtButton = new javax.swing.JButton();

        addMatchDialog.setAlwaysOnTop(true);
        addMatchDialog.setResizable(false);

        player2ComboxBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joureur 1", "Joueur 2", "Joueur 3", "Joueur 4", "Joueur 5", "Joueur 6", "Joueur 7", "Joueur 8" }));

        player1ComboxBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joureur 1", "Joueur 2", "Joueur 3", "Joueur 4", "Joueur 5", "Joueur 6", "Joueur 7", "Joueur 8" }));

        player3ComboxBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joureur 1", "Joueur 2", "Joueur 3", "Joueur 4", "Joueur 5", "Joueur 6", "Joueur 7", "Joueur 8" }));

        player4ComboxBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joureur 1", "Joueur 2", "Joueur 3", "Joueur 4", "Joueur 5", "Joueur 6", "Joueur 7", "Joueur 8" }));

        versusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versusLabel.setText("vs");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ABED Karim", "BASTIEN Benoît", "BATTA Florent", "BEN EL HADJ Hakim", "BRISARD Jérôme", "BUQUET Ruddy", "DECHEPY Bastien", "DELAJOD Willy" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lineRefereesSelectionPane.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BROUSSET PIERRE", "CAYRE LUDOVIC", "GARCES JEROME", "POITE ROMAIN", "RAYNAL MATHIEU", "ROZIER JEREMY" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ballBoySelectionPane.setViewportView(jList2);

        mainRefereeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABED Karim", "BASTIEN Benoît", "BATTA Florent", "BEN EL HADJ Hakim", "BRISARD Jérôme", "BUQUET Ruddy", "DECHEPY Bastien", "DELAJOD Willy" }));
        mainRefereeComboBox.setPreferredSize(new java.awt.Dimension(124, 20));

        mainRefereeLabel.setText("Arbitre de chaise");

        lineRefereeLabel.setText("Arbitre de ligne");

        ballBoyLabel.setText("Ramasseur");

        matchDateLabel.setText("Date");

        matchDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dimanche 1", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche 2", " " }));

        matchTimeLabel.setText("Horraire");

        matchTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10h - 12h", "12h - 14h", "14h - 16h", "16h - 18h" }));

        playerLabel.setText("Joueurs du match");

        confirmAddButton.setText("OK");

        cancelAddButton.setText("Cancel");
        cancelAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddButtonActionPerformed(evt);
            }
        });

        addMatchInfoLabel.setText("<html><p style=\"color:red;\">Informations si les valeurs rentrées ne sont pas correctes et risquent de dépasser<p><html>");

        addMatchTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addMatchTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMatchTitleLabel.setText("Ajouter / Modifier un Match");

        jLabel1.setText("Court");

        matchDateComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central", "Annexe 1", "Annexe 2", "Annexe 3" }));

        javax.swing.GroupLayout addMatchDialogLayout = new javax.swing.GroupLayout(addMatchDialog.getContentPane());
        addMatchDialog.getContentPane().setLayout(addMatchDialogLayout);
        addMatchDialogLayout.setHorizontalGroup(
            addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMatchDialogLayout.createSequentialGroup()
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addMatchDialogLayout.createSequentialGroup()
                                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(matchDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                .addGap(2, 2, 2))
                            .addGroup(addMatchDialogLayout.createSequentialGroup()
                                .addComponent(matchDateLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addMatchDialogLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(ballBoyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addMatchDialogLayout.createSequentialGroup()
                                    .addComponent(confirmAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(addMatchInfoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(addMatchTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineRefereeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainRefereeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatchDialogLayout.createSequentialGroup()
                                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lineRefereesSelectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(player1ComboxBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 124, Short.MAX_VALUE)
                                        .addComponent(player3ComboxBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(mainRefereeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(versusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(matchDateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addMatchDialogLayout.createSequentialGroup()
                                    .addComponent(matchDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(matchTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(matchTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player4ComboxBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ballBoySelectionPane)
                            .addComponent(player2ComboxBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 79, Short.MAX_VALUE))
        );
        addMatchDialogLayout.setVerticalGroup(
            addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatchDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMatchTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchDateLabel)
                    .addComponent(matchDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matchTimeLabel)
                    .addComponent(matchTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matchDateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(playerLabel)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matchDateLabel1)
                            .addComponent(player2ComboxBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player4ComboxBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addMatchDialogLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versusLabel)
                            .addComponent(player1ComboxBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3ComboxBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainRefereeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainRefereeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineRefereeLabel)
                    .addComponent(ballBoyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineRefereesSelectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ballBoySelectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMatchInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAddButton)
                    .addComponent(cancelAddButton))
                .addGap(11, 11, 11))
        );

        addMatchInfoLabel.getAccessibleContext().setAccessibleName("");

        saveCourtDialog.setAlwaysOnTop(true);

        saveDateLabel.setText("Date");

        saveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dimanche 1", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche 2", " " }));

        saveTimeLabel.setText("Horraire");

        saveTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10h - 12h", "12h - 14h", "14h - 16h", "16h - 18h" }));

        saveTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveTitleLabel.setText("Réserver un court");

        confirmSaveButton.setText("OK");

        cancelSaveButton.setText("Cancel");
        cancelSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSaveButtonActionPerformed(evt);
            }
        });

        saveCourtInfoLabel.setText("<html><p style=\"color:red;\">Informations si les valeurs rentrées ne sont pas correctes et risquent de dépasser<p><html>");

        javax.swing.GroupLayout saveCourtDialogLayout = new javax.swing.GroupLayout(saveCourtDialog.getContentPane());
        saveCourtDialog.getContentPane().setLayout(saveCourtDialogLayout);
        saveCourtDialogLayout.setHorizontalGroup(
            saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCourtDialogLayout.createSequentialGroup()
                .addGroup(saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveCourtDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(saveCourtDialogLayout.createSequentialGroup()
                                .addComponent(confirmSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(saveCourtDialogLayout.createSequentialGroup()
                                    .addComponent(saveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveTimeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(saveCourtInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(saveCourtDialogLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(saveTitleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saveCourtDialogLayout.setVerticalGroup(
            saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCourtDialogLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(saveTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDateLabel)
                    .addComponent(saveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveTimeLabel)
                    .addComponent(saveTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveCourtInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCourtDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelSaveButton)
                    .addComponent(confirmSaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planning des Matchs");
        setBackground(new java.awt.Color(240, 0, 0));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);

        title.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Planning du court central");

        courtComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        courtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central", "Annexe 1", "Annexe 2", "Annexe 3" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10-12h", "", null, null, null, null, null, null, null},
                {"12h-14h", null, null, null, null, null, null, null, null},
                {"14h-16h", null, null, null, null, null, null, null, null},
                {"16h-18h", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        addMatchButton.setText("Ajouter un match");
        addMatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatchButtonActionPerformed(evt);
            }
        });

        saveCourtButton.setText("Réserver un terrain");
        saveCourtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCourtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveCourtButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addMatchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMatchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveCourtButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatchButtonActionPerformed
        addMatchDialog.setVisible(true);
        addMatchDialog.setSize(470, 640);
    }//GEN-LAST:event_addMatchButtonActionPerformed

    private void saveCourtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCourtButtonActionPerformed
        saveCourtDialog.setVisible(true);
        saveCourtDialog.setSize(400, 200);
    }//GEN-LAST:event_saveCourtButtonActionPerformed

    private void cancelSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSaveButtonActionPerformed
        saveCourtDialog.setVisible(false);
    }//GEN-LAST:event_cancelSaveButtonActionPerformed

    private void cancelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddButtonActionPerformed
        addMatchDialog.setVisible(false);
    }//GEN-LAST:event_cancelAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { 
                    dataSourceDAO = OracleDataSourceDAO.getOracleDataSourceDAO();
                    minibusDAO = new OracleMiniBusDAO(); 
                    minibusDAO.setDataSource(dataSourceDAO); 
                    connexionBD = dataSourceDAO.getConnection(); 
                    minibusDAO.setConnection(connexionBD); 
                } catch (SQLException | FileNotFoundException ex) { 

                } 
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMatchButton;
    private javax.swing.JDialog addMatchDialog;
    private javax.swing.JLabel addMatchInfoLabel;
    private javax.swing.JLabel addMatchTitleLabel;
    private javax.swing.JLabel ballBoyLabel;
    private javax.swing.JScrollPane ballBoySelectionPane;
    private javax.swing.JButton cancelAddButton;
    private javax.swing.JButton cancelSaveButton;
    private javax.swing.JButton confirmAddButton;
    private javax.swing.JButton confirmSaveButton;
    private javax.swing.JComboBox<String> courtComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lineRefereeLabel;
    private javax.swing.JScrollPane lineRefereesSelectionPane;
    private javax.swing.JComboBox<String> mainRefereeComboBox;
    private javax.swing.JLabel mainRefereeLabel;
    private javax.swing.JComboBox<String> matchDateComboBox;
    private javax.swing.JComboBox<String> matchDateComboBox1;
    private javax.swing.JLabel matchDateLabel;
    private javax.swing.JLabel matchDateLabel1;
    private javax.swing.JComboBox<String> matchTimeComboBox;
    private javax.swing.JLabel matchTimeLabel;
    private javax.swing.JComboBox<String> player1ComboxBox;
    private javax.swing.JComboBox<String> player2ComboxBox;
    private javax.swing.JComboBox<String> player3ComboxBox;
    private javax.swing.JComboBox<String> player4ComboxBox;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JButton saveCourtButton;
    private javax.swing.JDialog saveCourtDialog;
    private javax.swing.JLabel saveCourtInfoLabel;
    private javax.swing.JComboBox<String> saveDateComboBox;
    private javax.swing.JLabel saveDateLabel;
    private javax.swing.JComboBox<String> saveTimeComboBox;
    private javax.swing.JLabel saveTimeLabel;
    private javax.swing.JLabel saveTitleLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel versusLabel;
    // End of variables declaration//GEN-END:variables
    
    private final List<MiniBus> listeMinibus; 
    private static IMiniBusDAO minibusDAO; 
    private static DataSource dataSourceDAO; 
    private static Connection connexionBD;
    
    private int indexMinibus = 0;
}
